# fly.toml app configuration file generated for food-manager-app on 2023-10-28T15:06:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "food-manager-app"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
